resources:
  - machineconfigpool.yaml
  - kubeletconfig.yaml
  - registry.yaml
  - ldap-secret.yaml
  - ldap_map.yaml
  - oc_service_account.yaml
  - ldap_cluster_role_binding.yaml
  - ldap-sync-configmap.yaml
  - ldap_sync_job.yaml
